### ISSUE TITLE
Closes group when changing combatant visibility

### ISSUE THREAD

**Issue by strongpauly** [vtt-lair/foundry-group-initiative#10]
A minor one, but a bit annoying when updating the visibility of multiple combatants.

I imagine there is no stored state about which groups are open, and it gets lost when the combat tracker gets re-rendered.

**Comment by vtt-lair** [comment]
It would seem that I've fixed this. Should be available later this week.

**Comment by vtt-lair** [comment]
No... no... I lied

**Comment by vtt-lair** [comment]
Found a fix for this, will be released a bit later the week
