### ISSUE TITLE
Does not work in Foundry V9

### ISSUE THREAD

**Issue by Zamrod** [vtt-lair/foundry-group-initiative#18]
It throws an error when you attempt to roll all NPCs in Foundry V9 Test 3. That error is:

group-initiative.js:103 Uncaught (in promise) TypeError: this.getCombatant is not a function
[Detected 1 package: group-initiative]
    at group-initiative.js:103
    at Array.reduce (<anonymous>)
    at Combat.rollGroupInitiative (group-initiative.js:98)
    at async Combat.rollNPC (group-initiative.js:57)
    at async MonksCombatTracker._onCombatControl (foundry.js:58142)

**Comment by vtt-lair** [comment]
Thanks! Will spend some time tomorrow to update this to the non-depreciated function

**Comment by vtt-lair** [comment]
I've just released a new version that should no longer have the error in v9 and also still work in 8. Please let me know once you've had a look if that fixed the issue. I've replaced the call to the depreciated function with the correct one.

**Comment by Zamrod** [comment]
This appears to work.
