### ISSUE TITLE
Adding Combatants Mid-Combat tries to perform actions on Non-GM Players

### ISSUE THREAD

**Issue by Aeristoka** [vtt-lair/foundry-group-initiative#24]
![group_initiative_error](https://user-images.githubusercontent.com/7988297/147893886-62843d91-2322-4a3d-bef3-8c16d929fc48.png)

Had a combat last night where I had a couple phases of combatants come in. Every time I added combatants the Module tried to have ALL players (8 of us, only myself with GM role) perform the add action. Above are the errors from a player's perspective.

**Comment by vtt-lair** [comment]
I'm not able to replicate this issue. 

Can you possibly share the following with me, want to see if there is something different:

- Your player permissions 
- What system are you playing (DnD 5e, PF2e etc. etc)

**Comment by vtt-lair** [comment]
I've created a new task to refactor the headers: #29

**Comment by Aeristoka** [comment]
> I'm not able to replicate this issue.
> 
> Can you possibly share the following with me, want to see if there is something different:
> 
> * Your player permissions
> * What system are you playing (DnD 5e, PF2e etc. etc)

Specifically DnD5e

Players have "Trusted Player" permission.
