### ISSUE TITLE
Groups unrelated combattants together in v9

### ISSUE THREAD

**Issue by strongpauly** [vtt-lair/foundry-group-initiative#26]
<img width="1840" alt="group-initiative-bug" src="https://user-images.githubusercontent.com/853954/148682306-4b51d4f7-9f64-4ee8-89a4-eab5e935d991.png">

**Comment by Aeristoka** [comment]
I can confirm this:
![image](https://user-images.githubusercontent.com/7988297/148685957-22a7c507-905b-4a74-9ac0-4de99dc06b85.png)

It seems to MOSTLY group them right after you've rolled, unless you happen to have a matched initiative roll, in which case it will keep an un-related Creature in the group, and sometimes kick out a related creature.

**Comment by Aeristoka** [comment]
Would it perhaps be possible to add a quick option to disable the grouping while this and #27 are worked on? I love the grouped initiative, it just seems like the expandable groups were a little ambitious and buggy at the moment.

**Comment by vtt-lair** [comment]
@Aeristoka I think that's an excellent idea. The grouping was actually pull from the original branch and was developed by someone else. I'll add a setting that allows you to disable this, while I work out the kinks with the grouping.

**Comment by vtt-lair** [comment]
I'm going to release a version that wraps the grouping with a setting. This way you can disable the grouping while I try and refactor the code for this. Unfortunately the grouping code is inherited code from the original code repo.

This way you can opt-in for the grouping or opt-out (by default) while I try and sort this out.

Sorry for the inconvenience.

**Comment by vtt-lair** [comment]
I've created a new task to refactor the headers: #29
