### ISSUE TITLE
Matched Initiative on non-like Creatures ends up with 1 like creature kicked out of group, and the non-like creature added

### ISSUE THREAD

**Issue by Aeristoka** [vtt-lair/foundry-group-initiative#27]
![image](https://user-images.githubusercontent.com/7988297/148686051-9e2f5866-727a-468d-8229-2766c2d52474.png)

Happens with any number of creatures that match initiative rolls with a group.

**Comment by vtt-lair** [comment]
I've created a new task to refactor the headers: #29
