### ISSUE TITLE
Throws an error when saving/closing the combat tracker settings

### ISSUE THREAD

**Issue by Koalahund** [vtt-lair/foundry-group-initiative#33]
Version:
![4af9243ddf5a37fa9ddb783be6e4e0ef](https://user-images.githubusercontent.com/85458282/149719499-794a989e-db3f-4ed8-a515-8189391f2b51.png)

Reproduce:
Open the combat tracker settings
change something and press save OR just close it
Error thrown
![37d164217656b9f77b671ee61425afa8](https://user-images.githubusercontent.com/85458282/149719041-eb2b03f3-a0d6-4aaf-aab2-d04d7b16c0f7.png)

**Comment by vtt-lair** [comment]
This has been fixed with the new release.
