### ISSUE TITLE
[Issue] FoundryVtt Ver 9 Issues? Try reinstalling. (Issues came back after a shortwhile)

### ISSUE THREAD

**Issue by UnoriginalDM** [vtt-lair/foundry-group-initiative#35]
I recently upgraded my foundry to the latest ver9 and was running into issues with this mod. While it was active, I could not use the "Roll All", "Roll NPC", or the individual roll (d20 icon) buttons thus I would have to set my initiatives by hand.  I saw a few other mod developers recently recommend reinstalling if their mod stopped working. I tried it with this mod and so far it has been working.

**Comment by OregonPinkRose** [comment]
Just worked for me.
Thank you!

**Comment by UnoriginalDM** [comment]
After 1 session issues started to come back unfortunately.
![image](https://user-images.githubusercontent.com/77896718/152881975-99078544-be09-4981-98d5-f27d8df4d030.png)

**Comment by vtt-lair** [comment]
@UnoriginalDM that section of code is part of the grouping functionality that is flagged as experimental. It's code that I inherited when taking the module over from the original developer that was no longer maintaining it. I need to redo that and have created a task for this #29.

To ensure you don't get that error (and a lot of other funky behaviour with regards to grouping the initiative), go to the Combat Tracker's settings:
![image](https://user-images.githubusercontent.com/33215552/152938530-b0b3c1c7-62a0-4660-85fc-65c4868a39c7.png)

And disable the experimental one:
![image](https://user-images.githubusercontent.com/33215552/152938569-8e2ceb82-b35a-4cc3-b56f-50c68e2c322b.png)

I'm going to close this ticket as I do have a ticket to refactor the grouping. Which I'll get to at some point... moving to a new country at the end of this month, so just focused on that for now.
