### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by heyzoms** [vtt-lair/foundry-group-initiative#38]
every time I have a group in my initiative and click the arrow to go past that group, to one of my players it goes back to the top of the group initiative and then repeatedly cycles through the group initiative until my game crashes

**Comment by vtt-lair** [comment]
Sorry I have been so quiet, I moved to a different country at the end of February and it's been a hectic past 5 months. Hope to get to issues loaded in the next few weeks.

**Comment by vtt-lair** [comment]
@heyzoms, is this with the Group Same Actor setting?
![image](https://user-images.githubusercontent.com/33215552/184671235-ea7f0d52-3f2c-4f47-8f55-417c41cb033c.png)

As that setting is still very buggy and haven't tried to refactor that at all yet and would advise to disable it for now.

If however, this is not related. I'm releasing a new version later this week that fixes a few things. So can test it with that new release too? Will comment here when it's released.

**Comment by heyzoms** [comment]
Seems to working! thanks! and no I don't use the experimental feature.
 sorry for late responses don't get on this site very much.
