### ISSUE TITLE
Creatures are listed as grouped even when they aren't

### ISSUE THREAD

**Issue by Zamrod** [vtt-lair/foundry-group-initiative#4]
If you click the roll all button in initiative the card for all the creatures says "grouped" even if there is only one of that creature. I'm not sure this is intended and it might be misleading.

**Comment by vtt-lair** [comment]
@Zamrod can you possibly share a screenshot of what happens? I've just added a bunch of creatures and PC's and click the "Roll All" and it created groups (when there were more than one) and not-groups (for single creatures/pc's) for the creatures as expected.

Also tried when there were just single creatures/pc's and that look correct as well.

**Comment by vtt-lair** [comment]
Believe I found a fix for this, will be released a bit later the week
