### ISSUE TITLE
Module is not showing up in module list and is not active.

### ISSUE THREAD

**Issue by mark-drury** [vtt-lair/foundry-group-initiative#41]
Installed module via forge, but the module is not functional, does not show up on the module list. The combat tracker pane has only the standard entries in it, no group initiative enhancements. Running V9

**Comment by vtt-lair** [comment]
Which version of the module is loaded?

**Comment by mark-drury** [comment]
2.1.0 is the most recent version on forge marketplace.

Thanks for the reply btw, love the module it really streamlines things.

**Comment by mark-drury** [comment]
I rolled back to v 2.0.5 and it started working again.

**Comment by vtt-lair** [comment]
Awesome at least there is a work around... think I'll flag 2.1.0 as v10 only. Obviously missed something when trying to make it valid for both.

**Comment by mark-drury** [comment]
Thanks for the swift reply, I have just checked up to 2.0.8 work its just as you say, the 2.1.0 that breaks. I will lock the updates on it until I upgrade to v10 in a month or so.

I really appreciate the work you put in, it is an awesome little mod and really helps me out as a DM..

Mark

**Comment by vtt-lair** [comment]
Thanks mark, glad you like the module. I've flag the latest version as version 10 only, so this problem shouldn't rear it's head for other people.
