### ISSUE TITLE
Latest release (2.1.3) is missing files

### ISSUE THREAD

**Issue by notrealdan** [vtt-lair/foundry-group-initiative#50]
The module.json and module.zip files are missing from the 2.1.3 release:
![image](https://user-images.githubusercontent.com/28198633/233804690-c64e14ab-82de-4182-8469-a8d3923fefe3.png)

This leads to an error on every check for module updates in Foundry, and of course an inability to install the update to 2.1.3:
![image](https://user-images.githubusercontent.com/28198633/233805093-c34c2f23-5054-497b-9cb2-d3952b4df0f7.png)

**Comment by vtt-lair** [comment]
O my gosh. I didn't notice that. The auto release didn't add the files. Let me fix that quickly

**Comment by vtt-lair** [comment]
Interesting. Release had the files, and then it was deleted for some reason

**Comment by vtt-lair** [comment]
Seems like the release has now been fixed. There's a possibility that you might have to re-install and uninstall again.
