### ISSUE TITLE
Needs a new version number

### ISSUE THREAD

**Issue by talmaru** [vtt-lair/foundry-group-initiative#51]
The version number needs to be updated for the new changes in order for Forge to pull the module down correctly.

![image](https://user-images.githubusercontent.com/6321213/234610410-59774008-3fc3-4e25-b143-72362e66d10d.png)

**Comment by vtt-lair** [comment]
Will get on it

**Comment by vtt-lair** [comment]
New version 2.14 has been released. Please try now and please let me know

**Comment by talmaru** [comment]
It is working again. Thanks :D
