### ISSUE TITLE
Can't get it to work for me

### ISSUE THREAD

**Issue by MagicalDayDreams** [vtt-lair/foundry-group-initiative#6]
Sorry to be a pain - running 5e on 0.8.9 via the Forge, everything up to date. I've selected the option for 'Roll Group Initiative' but it's still rolling for each participant separaretl
![Screenshot 2021-11-21 at 18 55 33](https://user-images.githubusercontent.com/94802417/142775262-7dc2f2fc-6c9d-4f48-b3eb-e0ca33bdbc8c.png)
![Screenshot 2021-11-21 at 18 56 01](https://user-images.githubusercontent.com/94802417/142775268-6bc67054-f8c2-498e-84ea-53111b3ea3db.png)
y.

**Comment by PepijnMC** [comment]
I had the same but at least for me the module "Mob Attack Tool" was the culprit. It's incompatible with this module now and disabling fixed it.

**Comment by MagicalDayDreams** [comment]
Thank you so much! Yes, it works fine now. That's a shame though because the combination of those two modules could really speed up some of my larger combats. Oh well!

**Comment by vtt-lair** [comment]
Thanks @PepijnMC and @MagicalDayDreams, will see what I can do to ensure this doesn't happen. I have Mob Attack Tool installed myself, so will see what happens here. I specifically renamed the functions etc in this module when I took it over, so that it didn't clash with Mob Attack Tool, but might be something I missed.

**Comment by vtt-lair** [comment]
Implemented a few fixes that seems to fix the clashing issue with Mob Attack Tool. I would advise if you do have Mob Attack Tool enabled, to disable the Group Initiative under the Module settings, just in case.

This will be released later this week.
