### ISSUE TITLE
Grouping Issue

### ISSUE THREAD

**Issue by Avitale34** [vtt-lair/foundry-group-initiative#8]
I am having an issue where I have 4 creatures all from the same actor but they do not group properly. I have 3 in a group and one on his own. But they are from the same exact actor.

![image](https://user-images.githubusercontent.com/65961637/142939183-69db147f-9d49-45be-bf64-759e61a32e56.png)

**Comment by vtt-lair** [comment]
Was the Assassin(2) added after rolling initiative? Or was it there from the get-go?

**Comment by vtt-lair** [comment]
@Avitale34 this seems to happen if you add a token to combat after rolling initiative. I've made a fix that I'll release this week still, to rather add the token to the already created group using that group's initiative.
