### ISSUE TITLE
Shows group to players even if all combatants have their visibility set to hidden

### ISSUE THREAD

**Issue by strongpauly** [vtt-lair/foundry-group-initiative#9]
If all the combatants contained within are group are set to hidden, it still shows the group to players, making it impossible to have hidden group combatants.

It also might be nice to be able to toggle all of the combatant's visibility from the group.

**Comment by strongpauly** [comment]
Just looked at this again, and couldn't reproduce it.  Not sure it always happens.  I had combat utility belt and turn marker alt modules enabled.

**Comment by vtt-lair** [comment]
Wasn't able to replicate this either... will keep and eye out however
